# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\raw-ui\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
from client.listenerToServer import *
from .chatScreen import *
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

LOG = assertLog()
class Ui_MainWindow(object):

    def __init__(self):
        self.serverChannel =    Peer2ServerListener() 
        self.serverChannel.connect_server()

    def register_request(self):
        print()
        username = self.te_username.text()
        password = self.te_password.text()

        result_register = self.serverChannel.request_register(username, password)
        print(result_register)
        
        if result_register[0] == 20:
            self.showMessageBox('Succesfully Registered')
            LOG.info("You registered [ {} ]".format(username))
            result_login = self.serverChannel.request_login(username, password)

            if result_login[0] == 21:
                LOG.info("You logined [ {} ]".format(username))
                self.open_chat()

            else:
                LOG.info("You could not login [ {} ]".format(username, password))
                self.showMessageBox('You could not Login')
        else:
            LOG.info("You could not registered [ {} ]".format(username, password))
            self.showMessageBox('You could not registered ')
            print(result_register[0])

    def login_request(self):
        username = self.te_username.text()
        password = self.te_password.text()

        result = self.serverChannel.request_login(username, password)
        if result[0] == 21:
            LOG.info("You logined [ {} ]".format(username, password))
            self.open_chat()
        else:
            LOG.info("You could not  [ {} ]".format(username, password))
            self.showMessageBox('You could not Login')

    def showMessageBox(self,message):
        msgBox = QMessageBox()
        # msgBox.setIcon(QMessageBox.Warning)
        msgBox.setWindowTitle('Message Box')
        msgBox.setText(message)
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec_()


    def open_chat(self):
        
        self.cwindow = QMainWindow()
        self.ui = Ui_ChatScreen(self.te_username.text(), self.te_password.text(), self.serverChannel, self.mainwindow)
        self.ui.setupUi(self.cwindow)
        self.mainwindow.hide()
        self.cwindow.show()
        # self.ui.hide()

    def setupUi(self, LoginScreen):
        self.mainwindow = LoginScreen
        LoginScreen.setObjectName(_fromUtf8("LoginScreen"))
        LoginScreen.resize(1000, 650)
        self.label = QtWidgets.QLabel(LoginScreen)
        self.label.setGeometry(QtCore.QRect(320, 270, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtWidgets.QLabel(LoginScreen)
        self.label_2.setGeometry(QtCore.QRect(320, 320, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))

        self.te_username = QtWidgets.QLineEdit(LoginScreen)
        self.te_username.setGeometry(QtCore.QRect(410, 260, 211, 31))
        self.te_username.setObjectName(_fromUtf8("te_username"))
        
        self.te_password = QtWidgets.QLineEdit(LoginScreen)
        self.te_password.setEchoMode(QLineEdit.Password)
        self.te_password.setGeometry(QtCore.QRect(410, 310, 211, 31))
        self.te_password.setObjectName(_fromUtf8("te_password"))
        self.label_3 = QtWidgets.QLabel(LoginScreen)
        self.label_3.setGeometry(QtCore.QRect(280, 140, 401, 71))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btn_login = QtWidgets.QPushButton(LoginScreen)
        self.btn_login.setGeometry(QtCore.QRect(410, 350, 93, 28))
        self.btn_login.setObjectName(_fromUtf8("btn_login"))
        self.btn_register = QtWidgets.QPushButton(LoginScreen)
        self.btn_register.setGeometry(QtCore.QRect(530, 350, 93, 28))
        self.btn_register.setObjectName(_fromUtf8("btn_register"))

        # ----------------------------------------------------------------

        self.btn_login.clicked.connect(self.login_request)
        self.btn_register.clicked.connect(self.register_request)
        # -----------------------------------------------------------------



        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        LoginScreen.setWindowTitle(_translate("LoginScreen", "P2P Chat Application", None))
        self.label.setText(_translate("LoginScreen", "Username : ", None))
        self.label_2.setText(_translate("LoginScreen", "Password : ", None))
        self.label_3.setText(_translate("LoginScreen", "P2P CHATT APPLICATION", None))
        self.btn_login.setText(_translate("LoginScreen", "Login", None))
        self.btn_register.setText(_translate("LoginScreen", "Register", None))

  